---
- hosts: aws_node_local
  become: true

  vars:
    # See group_vars/aws_node_local.yml, which pull vars from the environment.
    atl_product_family: "confluence"
    atl_product_user: "confluence"
    atl_product_edition: "confluence"

    atl_jdbc_encoding: 'UTF-8'
    atl_jdbc_collation: 'en_US.UTF-8'
  # Customizations added by bmeers
    atl_autologin_cookie_age: "10"
    atl_proxy_name:  "preprod-confluence.deloitte.com"
    atl_proxy_port:  "443"
    atl_ssl_proxy: "true"
    atl_tomcat_protocol: "org.apache.coyote.http11.Http11NioProtocol"
    atl_tomcat_scheme: "https"

  roles:
    - role: linux_common
    - role: aws_common
    - role: aws_shared_fs_config
    - role: product_common
    - role: product_install
      tags: [skip_on_stack_update]
    - role: database_init
      tags: [skip_on_stack_update]
    - role: restore_backups
    - role: confluence_common
    - role: confluence_config
    - role: product_startup
