---
- hosts: aws_node_local
  become: true

  vars:
    # See group_vars/aws_node_local.yml, which pull vars from the environment.
    atl_product_family: "jira"
    atl_product_user: "jira"
    atl_product_edition: "jira-{{ lookup('env', 'ATL_PRODUCT_EDITION') | lower }}"
    atl_install_jsd_as_obr: "{{ lookup('env', 'ATL_JSD_ASOBR') }}"
    atl_systemd_service_name: "jira.service"

    atl_startup_systemd_params:
      - "LimitNOFILE=16384"

    atl_jdbc_encoding: 'UNICODE'
    atl_jdbc_collation: 'C'
    atl_jdbc_ctype: 'C'
    atl_jdbc_template: 'template0'
    # Customizatios added by bmeers
    atl_efs_id: fs-1a75191f
    #Don't connect to the DR DB until restored data is in the correct structure -- up a folder
    #atl_db_host: de-dr-jira-db.cfbq6dvpjtws.us-west-2.rds.amazonaws.com
    #    atl_proxy_name:  "jira.deloitte.com"
    #    atl_proxy_port:  "443"
    #    atl_tomcat_scheme: "https"
    #    atl_tomcat_secure: "secure"
    # In case of DR, comment the following 2 lines and uncomment the above 4 lines so that the DR environment goes to the production URL. Once correct, kill node.
    atl_proxy_port:  "80"
    atl_tomcat_scheme: "http"

  roles:
    - role: linux_common
    - role: aws_common
    - role: aws_shared_fs_config
    - role: product_common
    - role: product_install
      tags: [skip_on_stack_update]
    - role: database_init
      tags: [skip_on_stack_update]
    - role: restore_backups
    - role: jira_config
    - role: product_startup
